name: CI

on: [push, pull_request]

jobs:
  without_env:
    runs-on: ubuntu-latest

    steps:
      - name: Echo MYCOLOR
        run: echo "MYCOLOR is ${{ vars.MYCOLOR }}"

      - name: Echo Show MYSECRET
        run: echo "MYSECRET is ${{ secrets.MYSECRET }}"

  with_env:
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://example.com

    steps:
      - name: Echo MYCOLOR
        run: echo "MYCOLOR is ${{ vars.MYCOLOR }}"

      - name: Echo Show MYSECRET
        run: echo "MYSECRET is ${{ secrets.MYSECRET }}"

